DNN_model_params:
  activation: relu
  batch_size: 1024
  epochs: 6
  loss: mse
  optimizer: adam
LSTM_model_params:
  batch_size: 32
  dropout: 0.2
  epochs: 6
  learning_rate: 0.001
  metrics: mae
LSTMpreprocessing:
  enable_daytime_index: true
  keep_daily_avg:
  - true
  - true
  - true
  - true
  keep_monthly_avg:
  - true
  - true
  - true
  - true
  shifts: 10
  test_size: 0.2
XGBRegressorModelParams:
  colsample_bytree: 0.9
  eval_metric: mphe
  learning_rate: 0.005
  max_depth: 6
  min_child_weight: 4
  n_estimators: 1500
  reg_alpha: 0.5
  reg_lambda: 1.5
  subsample: 0.9
  tree_method: exact
ard:
  alpha_1: 1e-08
  alpha_2: 1e-08
  compute_score: true
  lambda_1: 1e-07
  lambda_2: 1e-08
  n_iter: 1000
  tol: 0.001
dataset: loadCurveOneFull
preprocessing:
  columns:
  - t1
  - r1
  - holiday
  - schoolHoliday
  enable_daytime_index: true
  keep_daily_avg:
  - true
  - true
  - true
  - true
  keep_monthly_avg:
  - true
  - true
  - true
  - true
  neg_shifts: -3
  shifts: 3
  test_size: 0.2
  val_size: 0.1
