dataset : 'loadCurveThree'
XGBRegressorModelParams:
  n_estimators: 2000
  max_depth: 6
  learning_rate: 0.005
  colsample_bytree: 0.9
  min_child_weight: 4
  tree_method: 'exact'
  eval_metric: 'mphe'
  subsample: 0.9
  reg_alpha: 0.5
  reg_lambda: 1.5
DNN_model_params:
  epochs: 1
  batch_size: 32
  optimizer: 'adam'
  loss: 'mse'
  activation: 'relu'
preprocessing:
  test_size: 0.2
  colums: [ 't1' , 'r1']
  shifts: 3
  negShifts: -3