dataset : 'loadCurveTwo'
XGBRegressorModelParams:
  n_estimators: 1500
  max_depth: 6
  learning_rate: 0.005
  colsample_bytree: 0.9
  min_child_weight: 4
  tree_method: 'exact'
  eval_metric: 'mphe'
  subsample: 0.9
  reg_alpha: 0.5
  reg_lambda: 1.5
DNN_model_params:
  epochs: 6
  batch_size: 1024
  optimizer: 'adam'
  loss: 'mse'
  activation: 'relu'
preprocessing:
  test_size: 0.2
  colums: [ 't1' , 'r1',  'holiday', 'schoolHoliday']
  shifts: 3
  negShifts: -3
  enable_daytime_index: True
  monthlyCols: [ 't1' , 'r1' ]
  keepMonthlyAvg: [True, True, True, True]
  dailyCols: [ 't1' , 'r1' ]
  keepDailyAvg: [ True, True, True, True]
LSTMpreprocessing:
  test_size: 0.2
  shifts: 10
  enable_daytime_index: True
  monthlyCols: [ 't1' , 'r1' ]
  keepMonthlyAvg: [ True, True, True, True ]
  dailyCols: [ 't1' , 'r1' ]
  keepDailyAvg: [ True, True , True, True]
LSTM_model_params:
  epochs: 6
  batch_size: 32
  learning_rate: 0.001
  metrics: 'mae'
  dropout: 0.2