dataset : 'loadCurveTwoFull'
XGBRegressorModelParams:
  n_estimators: 1500
  max_depth: 6
  learning_rate: 0.005
  colsample_bytree: 0.9
  min_child_weight: 4
  tree_method: 'exact'
  eval_metric: 'mphe'
  subsample: 0.9
  reg_alpha: 0.5
  reg_lambda: 1.5
DNN_model_params:
  epochs: 6
  batch_size: 1024
  optimizer: 'adam'
  loss: 'mse'
  activation: 'relu'
preprocessing:
  test_size: 0.2
  val_size: 0.1
  columns: [ 't1' , 'r1',  'holiday', 'schoolHoliday']
  shifts: 3
  neg_shifts: -3
  enable_daytime_index: True
  monthly_cols: [ 't1' , 'r1' ]
  keep_monthly_avg: [True, True, True, True]
  daily_cols: [ 't1' , 'r1' ]
  keep_daily_avg: [ True, True, True, True]
LSTMpreprocessing:
  test_size: 0.2
  shifts: 10
  enable_daytime_index: True
  monthly_cols: [ 't1' , 'r1' ]
  keep_monthly_avg: [ True, True, True, True ]
  daily_cols: [ 't1' , 'r1' ]
  keep_daily_avg: [ True, True , True, True]
LSTM_model_params:
  epochs: 6
  batch_size: 32
  learning_rate: 0.001
  metrics: 'mae'
  dropout: 0.2
ard:
  alpha_1: 1e-08
  alpha_2: 1e-08
  compute_score: True
  lambda_1: 1e-07
  lambda_2: 1e-08
  n_iter: 1000
  tol: 0.001